<?php


/**
 * [BEGIN_COT_EXT]
 * Code=r301
 * Name=r301
 * Description=Makes 301 redirects and rewrites urls easy
 * Version=1.5.0
 * Date=2011-10-16
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=R
 * Requires_plugins=urleditor
 * [END_COT_EXT]
 * 
 * [BEGIN_COT_EXT_CONFIG]
 * defdates=01:select:0,7,15,30,60,90:30:
 * [END_COT_EXT_CONFIG]
 * 
 *  */

/**
 * plugin r301 for Cotonti Siena
 * 
 * @package r301
 * @version 1.5.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>
