<?php
/**
 * plugin r301 for Cotonti Siena
 * 
 * @package r301
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['cfg_defdates'] = array('По умолчанию дата истекает через');

$L['301_from'] = 'Исходно';
$L['301_to'] = 'Заменить';
$L['301_regex'] = 'Регулярка';
$L['301_date'] = 'Истекает';
$L['301_type'] = 'Тип';

?>