<?php
/**
 * plugin r301 for Cotonti Siena
 * 
 * @package r301
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

$L['cfg_defdates'] = array('Date expires after days by default');

$L['301_from'] = 'Replace From';
$L['301_to'] = 'Replace To';
$L['301_regex'] = 'Regex';
$L['301_date'] = 'Expires';
$L['301_type'] = 'Type';

?>